/**
 * \file
 *
 * \brief sensor board demo, connect to Ali Cloud.
 *
 * Copyright (c) 2017-2018 Microchip Technology Inc. and its subsidiaries. 
 * You may use this software and any derivatives exclusively with Microchip 
 * products.
 *
 *
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE,
 * INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY,
 * AND FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT WILL MICROCHIP BE
 * LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL
 * LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND WHATSOEVER RELATED TO THE
 * SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS BEEN ADVISED OF THE
 * POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE FULLEST EXTENT
 * ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN ANY WAY
 * RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
 * THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 *
 */
#ifndef _VERSION_H_
#define _VERSION_H_

/* Release version */
#define SW_VERSION_MAJOR	1

/* Development version */
#define SW_VERSION_MINOR	0


#define CRYPTO_LIB_MAJOR_VERSION  2    //! AWS IoT Zero Touch major version number
#define CRYPTO_LIB_API_VERSION    2    //! AWS IoT Zero Touch API version number
#define CRYPTO_LIB_PATCH_VERSION  4    //! AWS IoT Zero Touch patch version number

#define STRING2(x)  #x
#define STRING(x)   STRING2(x)

//! AWS IoT Zero Touch version string (Example: "1.0.0")
#define VERSION_STRING       STRING(CRYPTO_LIB_MAJOR_VERSION) "." \
STRING(CRYPTO_LIB_API_VERSION) "." \
STRING(CRYPTO_LIB_PATCH_VERSION)

//! AWS IoT Zero Touch long version string (Example: "AWS IoT Zero Touch Demo v1.0.0")
#define VERSION_STRING_LONG  "AWS IoT Zero Touch Demo v" VERSION_STRING


#endif // _VERSION_H_
